### ISSUE TITLE
How to configure laravel application to work with file upload over api

### ISSUE THREAD

**Issue by stojankukrika** [spatie/laravel-cors#13] opened 2018-02-09 08:04 UTC
I build some web application based on laravel 5.5 framework and build api which use Ionic 3 to build mobile applications. But have a problem with upload file(video) because I can't send it over base64 it's too large for that propose and try with file upload but it looks like that cors stop him to do that. 
Because all works in local network but when I put it on dev server it's didn't work, a body is empty (the only header is sent without data and file). 
I add in Laravel website this package for cors and it's didn't work, it's work for other endpoints but for that, it's didn't. Can anybody have the same problem and how to solve it?

**Comment by AlexVanderbist** [comment] 2018-02-09 13:58
Hi! This doesn't sound like a problem with the CORS package (but I may be wrong)...

Can you try to upload a file on your application (on the live server) with the network tab opened? Do the CORS requests (HEAD) all return `200 OK`? Do the returned headers make sense? Feel free to attach a screenshot of the HEAD requests here and we'll take a look at it.

**Comment by stojankukrika** [comment] 2018-02-12 07:47
He returns 200 but the body is an empty array, that I get when dd($request->all()) but the header is ok, have a token. When I test it locally I get file normally in the body which I can use.

**Comment by freekmurze** [comment] 2018-02-12 08:32
I'm thinking your problem isn't caused by this package. If your request is stopped due to cors constraints, you'll see it in the response: https://github.com/spatie/laravel-cors/blob/61966da0a7d718d4ef8151d6e9a9b2b946646848/src/Cors.php#L72

Closing this for now. If you find out that this package did indeed cause this problem, feel free to open up an new issue.

**Closed as completed by freekmurze** 2018-02-12 08:32 UTC

**Comment by stojankukrika** [comment] 2018-02-12 08:50
ok. Maybe you are right because I didn't get 403.
